
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";




const AboutUs = lazy(() => import("./pages/AboutUs.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const Blog = lazy(() => import("./pages/Blog.tsx"));
const Blog7WaysGolfCoursesCanGoGreen = lazy(() => import("./pages/Blog7WaysGolfCoursesCanGoGreen.tsx"));
const BlogAreEcoGolfBallsSafeForFishAndOceans = lazy(() => import("./pages/BlogAreEcoGolfBallsSafeForFishAndOceans.tsx"));
const BlogBiggestIssueInSustainability = lazy(() => import("./pages/BlogBiggestIssueInSustainability.tsx"));
const BlogBiodegradableGolfBallsEcoFriendlyPractice = lazy(() => import("./pages/BlogBiodegradableGolfBallsEcoFriendlyPractice.tsx"));
const BlogBiodegradableGolfBallsMaterials = lazy(() => import("./pages/BlogBiodegradableGolfBallsMaterials.tsx"));
const BlogBiodegradableVsConventional = lazy(() => import("./pages/BlogBiodegradableVsConventional.tsx"));
const BlogCanYouHitGolfBallsIntoLakes = lazy(() => import("./pages/BlogCanYouHitGolfBallsIntoLakes.tsx"));
const BlogFromTeeToSea = lazy(() => import("./pages/BlogFromTeeToSea.tsx"));
const BlogIsGolfHurtingNature = lazy(() => import("./pages/BlogIsGolfHurtingNature.tsx"));
const BlogPlayGreenlyVsOtherEcoGolfBalls = lazy(() => import("./pages/BlogPlayGreenlyVsOtherEcoGolfBalls.tsx"));
const BlogRedirect = lazy(() => import("./pages/BlogRedirect.tsx"));
const BlogSportsFloorMarkingTape = lazy(() => import("./pages/BlogSportsFloorMarkingTape.tsx"));
const BlogTeeOffWithABiodegradableGolfBall = lazy(() => import("./pages/BlogTeeOffWithABiodegradableGolfBall.tsx"));
const ContactUs = lazy(() => import("./pages/ContactUs.tsx"));
const CopyBlog = lazy(() => import("./pages/CopyBlog.tsx"));
const PrivacyPolicy = lazy(() => import("./pages/PrivacyPolicy.tsx"));

export const userRoutes: RouteObject[] = [



	{ path: "/about-us", element: <AboutUs />},
	{ path: "/aboutus", element: <AboutUs />},
	{ path: "/", element: <App />},
	{ path: "/blog", element: <Blog />},
	{ path: "/blog7ways-golf-courses-can-go-green", element: <Blog7WaysGolfCoursesCanGoGreen />},
	{ path: "/blog7waysgolfcoursescangogreen", element: <Blog7WaysGolfCoursesCanGoGreen />},
	{ path: "/blog-are-eco-golf-balls-safe-for-fish-and-oceans", element: <BlogAreEcoGolfBallsSafeForFishAndOceans />},
	{ path: "/blogareecogolfballssafeforfishandoceans", element: <BlogAreEcoGolfBallsSafeForFishAndOceans />},
	{ path: "/blog-biggest-issue-in-sustainability", element: <BlogBiggestIssueInSustainability />},
	{ path: "/blogbiggestissueinsustainability", element: <BlogBiggestIssueInSustainability />},
	{ path: "/blog-biodegradable-golf-balls-eco-friendly-practice", element: <BlogBiodegradableGolfBallsEcoFriendlyPractice />},
	{ path: "/blogbiodegradablegolfballsecofriendlypractice", element: <BlogBiodegradableGolfBallsEcoFriendlyPractice />},
	{ path: "/blog-biodegradable-golf-balls-materials", element: <BlogBiodegradableGolfBallsMaterials />},
	{ path: "/blogbiodegradablegolfballsmaterials", element: <BlogBiodegradableGolfBallsMaterials />},
	{ path: "/blog-biodegradable-vs-conventional", element: <BlogBiodegradableVsConventional />},
	{ path: "/blogbiodegradablevsconventional", element: <BlogBiodegradableVsConventional />},
	{ path: "/blog-can-you-hit-golf-balls-into-lakes", element: <BlogCanYouHitGolfBallsIntoLakes />},
	{ path: "/blogcanyouhitgolfballsintolakes", element: <BlogCanYouHitGolfBallsIntoLakes />},
	{ path: "/blog-from-tee-to-sea", element: <BlogFromTeeToSea />},
	{ path: "/blogfromteetosea", element: <BlogFromTeeToSea />},
	{ path: "/blog-is-golf-hurting-nature", element: <BlogIsGolfHurtingNature />},
	{ path: "/blogisgolfhurtingnature", element: <BlogIsGolfHurtingNature />},
	{ path: "/blog-play-greenly-vs-other-eco-golf-balls", element: <BlogPlayGreenlyVsOtherEcoGolfBalls />},
	{ path: "/blogplaygreenlyvsotherecogolfballs", element: <BlogPlayGreenlyVsOtherEcoGolfBalls />},
	{ path: "/blog-redirect", element: <BlogRedirect />},
	{ path: "/blogredirect", element: <BlogRedirect />},
	{ path: "/blog-sports-floor-marking-tape", element: <BlogSportsFloorMarkingTape />},
	{ path: "/blogsportsfloormarkingtape", element: <BlogSportsFloorMarkingTape />},
	{ path: "/blog-tee-off-with-a-biodegradable-golf-ball", element: <BlogTeeOffWithABiodegradableGolfBall />},
	{ path: "/blogteeoffwithabiodegradablegolfball", element: <BlogTeeOffWithABiodegradableGolfBall />},
	{ path: "/contact-us", element: <ContactUs />},
	{ path: "/contactus", element: <ContactUs />},
	{ path: "/copy-blog", element: <CopyBlog />},
	{ path: "/copyblog", element: <CopyBlog />},
	{ path: "/privacy-policy", element: <PrivacyPolicy />},
	{ path: "/privacypolicy", element: <PrivacyPolicy />},

];
